package:
  name: "spark-nlp"
  version: 2.3.4

app:
  entry: spark-nlp
  summary: Natural Language Understanding Library for Apache Spark.

source:
    fn: spark-nlp-2.3.4.tar.gz
    url: https://files.pythonhosted.org/packages/ec/bf/84886764ccd111c9be710954d43754ebbb638e9fa6a295600b676f5021fd/spark-nlp-2.3.4.tar.gz
    sha256: 10ef5b1671ab5e2ef5977e682d8d629ee26106c71679a02e2c284703f4419c2a
build:
  noarch: generic
  number: 0
  script: "python -m pip install . --no-deps -vv"

requirements:
  build:
    - python
  run:
    - python

about:
  home: https://github.com/JohnSnowLabs/spark-nlp/
  license: Apache License 2.0
  license_family: APACHE
  license_url: https://github.com/JohnSnowLabs/spark-nlp/blob/master/LICENSE
  description: John Snow Labs Spark-NLP is a natural language processing library built on top of Apache Spark ML. It provides simple, performant & accurate NLP annotations for machine learning pipelines, that scale easily in a distributed environment.
  summary: Natural Language Understanding Library for Apache Spark.
