package:
  name: "spark-nlp"
  version: 2.6.0

app:
  entry: spark-nlp
  summary: Natural Language Understanding Library for Apache Spark.

source:
    fn: spark-nlp-2.6.0.tar.gz
    url: https://files.pythonhosted.org/packages/2a/98/a1615193d6788ca68080508723082263a86e69f0815afa9a96309512a3ea/spark-nlp-2.6.0.tar.gz
    sha256: e2ccf713ba3c4407062ea52a4f40e8dced1b839f8fe9fa6a37b53bf44544ac81
build:
  noarch: generic
  number: 0
  script: "python -m pip install . --no-deps -vv"

requirements:
  build:
    - python
  run:
    - python

about:
  home: https://github.com/JohnSnowLabs/spark-nlp/
  license: Apache License 2.0
  license_family: APACHE
  license_url: https://github.com/JohnSnowLabs/spark-nlp/blob/master/LICENSE
  description: John Snow Labs Spark-NLP is a natural language processing library built on top of Apache Spark ML. It provides simple, performant & accurate NLP annotations for machine learning pipelines, that scale easily in a distributed environment.
  summary: Natural Language Understanding Library for Apache Spark.
