# This recipe requires the latest conda build that includes the icon handling fixes
package:
  name: "spark-nlp"
  version: 1.8.3

app:
  entry: spark-nlp
  summary: Natural Language Understanding Library for Apache Spark.

source:
    fn: spark-nlp-1.8.3.tar.gz 
    url: https://files.pythonhosted.org/packages/2f/9b/1a6ced611ff57565594c04ab56b0fde9f5fd97b02e2c4b97f2b8461bf553/spark-nlp-1.8.3.tar.gz
    sha256: e5e94ccb9f6946f478c701cc56a755f80ae30dde6b0013786b462103d5984cff
build:
  noarch: generic
  number: 0
  script: "python -m pip install . --no-deps -vv"

requirements:
  build:
    - python
  run:
    - python

about:
  home: https://github.com/JohnSnowLabs/spark-nlp/
  license: Apache License 2.0
  license_family: APACHE
  license_url: https://github.com/JohnSnowLabs/spark-nlp/blob/master/LICENSE
  description: John Snow Labs Spark-NLP is a natural language processing library built on top of Apache Spark ML. It provides simple, performant & accurate NLP annotations for machine learning pipelines, that scale easily in a distributed environment.
  summary: Natural Language Understanding Library for Apache Spark.
