# This recipe requires the latest conda build that includes the icon handling fixes
package:
  name: "spark-nlp"
  version: 2.0.4

app:
  entry: spark-nlp
  summary: Natural Language Understanding Library for Apache Spark.

source:
    fn: spark-nlp-2.0.4.tar.gz 
    url: https://files.pythonhosted.org/packages/c8/ae/0b158b92bb8d031accf4201a429a7ad1853712680635d3232ee1c29d200c/spark-nlp-2.0.4.tar.gz
    sha256: f6617b9ea506d796069577ddb5fc4762e5458abe5394c53e964515067e5ab0c2
build:
  noarch: generic
  number: 0
  script: "python -m pip install . --no-deps -vv"

requirements:
  build:
    - python
  run:
    - python

about:
  home: https://github.com/JohnSnowLabs/spark-nlp/
  license: Apache License 2.0
  license_family: APACHE
  license_url: https://github.com/JohnSnowLabs/spark-nlp/blob/master/LICENSE
  description: John Snow Labs Spark-NLP is a natural language processing library built on top of Apache Spark ML. It provides simple, performant & accurate NLP annotations for machine learning pipelines, that scale easily in a distributed environment.
  summary: Natural Language Understanding Library for Apache Spark.
