# This recipe requires the latest conda build that includes the icon handling fixes
package:
  name: "spark-nlp"
  version: 2.1.0

app:
  entry: spark-nlp
  summary: Natural Language Understanding Library for Apache Spark.

source:
    fn: spark-nlp-2.1.0.tar.gz
    url: https://files.pythonhosted.org/packages/88/85/47299755db5551ac546697a31af5f865eb94bda2f3a2914640caebbc067b/spark-nlp-2.1.0.tar.gz
    sha256: faf652e869722005b54a27ea22c6c638c4e989f4dd52f9ab5efa5c1b7f30b7ff
build:
  noarch: generic
  number: 0
  script: "python -m pip install . --no-deps -vv"

requirements:
  build:
    - python
  run:
    - python

about:
  home: https://github.com/JohnSnowLabs/spark-nlp/
  license: Apache License 2.0
  license_family: APACHE
  license_url: https://github.com/JohnSnowLabs/spark-nlp/blob/master/LICENSE
  description: John Snow Labs Spark-NLP is a natural language processing library built on top of Apache Spark ML. It provides simple, performant & accurate NLP annotations for machine learning pipelines, that scale easily in a distributed environment.
  summary: Natural Language Understanding Library for Apache Spark.
